services:
  opensearch-dev:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-dev
    environment:
      - cluster.name=${OPENSEARCH_DEV_CLUSTER_NAME}
      - discovery.type=single-node
      - bootstrap.memory_lock=${OPENSEARCH_DEV_BOOTSTRAP_MEMORY_LOCK:-true}
      - OPENSEARCH_JAVA_OPTS=${OPENSEARCH_DEV_JAVA_OPTS}
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-dev-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-dev-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: ${OPENSEARCH_DEV_HOSTS:-'["https://opensearch-dev:9200"]'}
    networks:
      - opensearch-dev-net

volumes:
  opensearch-dev-data:

networks:
  opensearch-dev-net:
    driver: bridge